apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: hello-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: default
  labels:
    app: hello-app
spec:
  selector:
    app: hello-app
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 80
     name: http 
     targetPort: 80
